sudo: required

services:
 - docker

language: bash

script:
# prepare qemu
 - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
 - docker build -t gilir/rpi-traefik:build .
# test image
 - docker run hypriot/rpi-traefik:build version
