version: '3'

services:
  traefik:
    image: gilir/rpi-traefik
    command:
      - --web
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=lavergne.online
      - --web.metrics
      - --web.metrics.prometheus
      - --logLevel=DEBUG
      - --checkNewVersion=false
      - --acme
      - --acme.email=julien@lavergne.online
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.entrypoint=https
      - --acme.ondemand=true
      - --acme.domains='lavergne.online,mastodon.lavergne.online,selfoss.lavergne.online,nextcloud.lavergne.online,blog.lavergne.online,isso.lavergne.online,wallabag.lavergne.online,gogs.lavergne.online,piwik.lavergne.online,grafana.lavergne.online'
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --defaultentrypoints=https,https
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - traefik_ssl:/etc/traefik/ssl
      - traefik_acme:/etc/traefik/acme
    environment:
      - "GID=901"
      - "UID=901"
    networks:
      - proxy-network

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  traefik_acme:
    external: true
  traefik_ssl:
    external: true
